### PR TITLE
added database migrations

### PR DESCRIPTION
**Pull request by howlowck**

### CODE REVIEW

**Comment by KSLHacks** [comment]
@howlowck let's schedule time to sync and go over `feature/database` this week.

**Comment by KSLHacks** [comment]
New requirement: this PR must close issue #26 

@howlowck

**Comment by howlowck** [comment]
@KSLHacks I updated the migrations. and changed the constraints to anticipate student data deletion.  Now, when a student is deleted, its related data's `student_id` will be set to null.

**Comment by KSLHacks** [comment]
@howlowck This was the biggest concern with issue #26. Based on our requirements, I approve these migrations.

**Comment by KSLHacks** [comment]
@howlowck this should be moved to `project-superior-api` repo

**Pull request closed without merging**
